"""Add socket support to equipment items

Revision ID: 213d2d45b552
Revises: be3eaf9bca93
Create Date: 2025-05-23 22:28:30.208432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213d2d45b552'
down_revision: Union[str, None] = 'be3eaf9bca93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add socket columns with default values first (nullable)
    op.add_column('equipment_items', sa.Column('sockets_basic', sa.Integer(), nullable=True, default=0))
    op.add_column('equipment_items', sa.Column('sockets_primary', sa.Integer(), nullable=True, default=0))
    op.add_column('equipment_items', sa.Column('sockets_vital', sa.Integer(), nullable=True, default=0))
    op.add_column('equipment_items', sa.Column('sockets_cloak', sa.Integer(), nullable=True, default=0))
    op.add_column('equipment_items', sa.Column('sockets_necklace', sa.Integer(), nullable=True, default=0))
    op.add_column('equipment_items', sa.Column('sockets_pvp', sa.Integer(), nullable=True, default=0))
    
    # Update existing rows to have 0 sockets
    op.execute("UPDATE equipment_items SET sockets_basic = 0 WHERE sockets_basic IS NULL")
    op.execute("UPDATE equipment_items SET sockets_primary = 0 WHERE sockets_primary IS NULL")
    op.execute("UPDATE equipment_items SET sockets_vital = 0 WHERE sockets_vital IS NULL")
    op.execute("UPDATE equipment_items SET sockets_cloak = 0 WHERE sockets_cloak IS NULL")
    op.execute("UPDATE equipment_items SET sockets_necklace = 0 WHERE sockets_necklace IS NULL")
    op.execute("UPDATE equipment_items SET sockets_pvp = 0 WHERE sockets_pvp IS NULL")
    
    # Make columns NOT NULL
    op.alter_column('equipment_items', 'sockets_basic', nullable=False)
    op.alter_column('equipment_items', 'sockets_primary', nullable=False)
    op.alter_column('equipment_items', 'sockets_vital', nullable=False)
    op.alter_column('equipment_items', 'sockets_cloak', nullable=False)
    op.alter_column('equipment_items', 'sockets_necklace', nullable=False)
    op.alter_column('equipment_items', 'sockets_pvp', nullable=False)
    
    # Skip constraint creation - it already exists
    # op.create_unique_constraint('uq_table_value', 'table_values', ['table_id', 'item_level'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_items', 'sockets_pvp')
    op.drop_column('equipment_items', 'sockets_necklace')
    op.drop_column('equipment_items', 'sockets_cloak')
    op.drop_column('equipment_items', 'sockets_vital')
    op.drop_column('equipment_items', 'sockets_primary')
    op.drop_column('equipment_items', 'sockets_basic')
    # ### end Alembic commands ###
