"""Add icon column to item_definitions

Revision ID: 2b5360e2266e
Revises: 4f34ed0afbcc
Create Date: 2025-05-22 21:13:06.850380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5360e2266e'
down_revision: Union[str, None] = '4f34ed0afbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_definitions', sa.Column('icon', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_definitions', 'icon')
    # ### end Alembic commands ###
