"""Add armour_type column to item_definitions

Revision ID: 4f34ed0afbcc
Revises: 12830c975d59
Create Date: 2025-05-22 17:58:02.510285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f34ed0afbcc'
down_revision: Union[str, None] = '12830c975d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_definitions', sa.Column('armour_type', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_item_definitions_armour_type'), 'item_definitions', ['armour_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_definitions_armour_type'), table_name='item_definitions')
    op.drop_column('item_definitions', 'armour_type')
    # ### end Alembic commands ###
