"""Create item_definition table

Revision ID: 4f5835961d06
Revises: 
Create Date: 2025-05-22 05:00:13.612277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5835961d06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_definitions',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_ilvl', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=50), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('required_player_level', sa.Integer(), nullable=False),
    sa.Column('scaling', sa.String(length=255), nullable=True),
    sa.Column('value_table_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # Only keep indexes for fields we'll query frequently
    op.create_index(op.f('ix_item_definitions_name'), 'item_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_item_definitions_slot'), 'item_definitions', ['slot'], unique=False)
    op.create_index(op.f('ix_item_definitions_base_ilvl'), 'item_definitions', ['base_ilvl'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_definitions_base_ilvl'), table_name='item_definitions')
    op.drop_index(op.f('ix_item_definitions_slot'), table_name='item_definitions')
    op.drop_index(op.f('ix_item_definitions_name'), table_name='item_definitions')
    op.drop_table('item_definitions')
    # ### end Alembic commands ###
