"""create progression tables

Revision ID: 5c7d691d5d36
Revises: 4f5835961d06
Create Date: 2025-05-22 14:41:23.993250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7d691d5d36'
down_revision: Union[str, None] = '4f5835961d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_tables',
    sa.Column('table_id', sa.String(length=50), nullable=False),
    sa.Column('progression_type', sa.Enum('LINEAR', 'ARRAY', name='progressiontype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_table('item_stats',
    sa.Column('item_key', sa.Integer(), nullable=False),
    sa.Column('stat_name', sa.String(length=50), nullable=False),
    sa.Column('value_table_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_key'], ['item_definitions.key'], ),
    sa.ForeignKeyConstraint(['value_table_id'], ['progression_tables.table_id'], ),
    sa.PrimaryKeyConstraint('item_key', 'stat_name')
    )
    op.create_table('table_values',
    sa.Column('table_id', sa.String(length=50), nullable=False),
    sa.Column('item_level', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['progression_tables.table_id'], ),
    sa.PrimaryKeyConstraint('table_id', 'item_level'),
    sa.UniqueConstraint('table_id', 'item_level', name='uq_table_value')
    )
    op.create_index(op.f('ix_item_definitions_quality'), 'item_definitions', ['quality'], unique=False)
    op.create_index(op.f('ix_item_definitions_required_player_level'), 'item_definitions', ['required_player_level'], unique=False)
    op.drop_column('item_definitions', 'value_table_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_definitions', sa.Column('value_table_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_definitions_required_player_level'), table_name='item_definitions')
    op.drop_index(op.f('ix_item_definitions_quality'), table_name='item_definitions')
    op.drop_table('table_values')
    op.drop_table('item_stats')
    op.drop_table('progression_tables')
    # ### end Alembic commands ###
