"""Add essence model for essence items

Revision ID: be3eaf9bca93
Revises: 0caec197d067
Create Date: 2025-05-23 21:28:40.248154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3eaf9bca93'
down_revision: Union[str, None] = '0caec197d067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essences',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('essence_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['key'], ['items.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_essences_essence_type'), 'essences', ['essence_type'], unique=False)
    op.create_index(op.f('ix_essences_tier'), 'essences', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_essences_tier'), table_name='essences')
    op.drop_index(op.f('ix_essences_essence_type'), table_name='essences')
    op.drop_table('essences')
    # ### end Alembic commands ###
