name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Create package structure
      run: |
        mkdir -p lotro_forge/lotro_forge
        mv models parsers lotro_forge/lotro_forge/
        mv tests lotro_forge/
        mv setup.py lotro_forge/
        mv requirements.txt lotro_forge/
        
    - name: Install dependencies
      working-directory: lotro_forge
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        
    - name: Run tests with coverage
      working-directory: lotro_forge
      run: |
        python -m pytest --cov=. --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./lotro_forge/coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Check coverage threshold
      working-directory: lotro_forge
      run: |
        coverage report --fail-under=90

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          lotro_forge/.coverage
          lotro_forge/coverage.xml
          lotro_forge/htmlcov/
        retention-days: 7 